In [2]:
from math import factorial

num = int(input())
factorial(num)

24

In [15]:
from math import factorial

k, n = map(int, input().split())

C = factorial(k) // (factorial(n)*factorial(k-n))
print(C)

21


SyntaxError: invalid syntax (3986697983.py, line 1)

In [27]:
from math import factorial

n, k = map(int, input().split())

С = (factorial(n+k-1)) // (factorial(k)*factorial(n-1))
print(С)

20


In [2]:
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)

In [126]:
df = iris.frame

df['Intercept'] = 1


In [128]:
X = df[["petal length (cm)" ,"petal width (cm)", "Intercept"]]
y = df["target"]

In [129]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [130]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [131]:
model.intercept_

array([ 10.4013265 ,   2.91912523, -13.32045173])

In [132]:
model.coef_

array([[-2.59194392e+00, -1.09782503e+00, -8.81557524e-03],
       [ 7.10011800e-02, -7.43229403e-01,  1.64293242e-03],
       [ 2.52094274e+00,  1.84105444e+00,  7.17264282e-03]])

In [134]:
from sklearn.linear_model import SGDRegressor


sgd_reg = SGDRegressor(penalty=None, eta0=0.002, random_state=42)
sgd_reg.fit(X_train, y_train)
n_epochs = 500

In [135]:
sgd_reg.intercept_

array([-0.0252555])

In [136]:
sgd_reg.coef_

array([ 0.26375546,  0.13169691, -0.0252555 ])

In [ ]:
from sklearn import dummy_feature



In [163]:
import numpy as np

def BGD(X, y):
    
    K = y.nunique()

    y = y.values
    X = X.values

    m = X.shape[0]
    n = X.shape[1]

    O = np.zeros([K, n])
    n_epochs = 5000
    p = np.zeros([m,K])

    for iter in range(n_epochs):
    
        s = X @ O.T

        
        exp_s = np.exp(s)
        p = exp_s / np.sum(exp_s, axis=1, keepdims=True)
        # Cross_entropy cost function derivative

        y_0_k = y == 0
        y_1_k = y == 1
        y_2_k = y == 2
        k = np.zeros([K,n])

        for i in range(K):
            if i == 0:
                y = y_0_k
            elif i == 1:
                y = y_1_k
            else: 
                y = y_2_k
            k[i] = 1/m * np.dot((p[:, i] - y).T, X)

        for i in range(K):
            O[i] =  O[i] - 0.5 * k[i]

    return p.argmax(axis=1)
BGD(X_train, y_train)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [164]:
p = BGD(X_train, y_train)

from sklearn.metrics import accuracy_score
accuracy_score(np.array(y_train), p)

0.3333333333333333

In [ ]:
from copy import deepcopy
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error


sgd_reg = LogisticRegression(random_state=42)
n_epochs = 500
best_valid_rmse = float('inf')

for epoch in range(n_epochs):
    BGD(X_train, y_train)
    y_valid_predict = sgd_reg.predict(X_test)
    val_error = mean_squared_error(y_test, y_valid_predict, squared=False)
    if val_error < best_valid_rmse:
        best_valid_rmse = val_error
        best_model = deepcopy(sgd_reg)